name: movizone
description: "A new Flutter project."
publish_to: 'none'
version:

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dartz:
  flutter:
    sdk: flutter
  flutter_animate:
  flutter_bloc:
  flutter_svg:
  hive:
  hive_flutter:
  http:
  smooth_page_indicator:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  hive_generator:
  build_runner:
  flutter_launcher_icons:
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true
  assets: 
    - assets/